### ISSUE TITLE
License Inquiry

### ISSUE THREAD

**Issue by mchip22** [xebialabs-community/xld-lock-plugin#2]
Which license is covering this plug-in?
The file https://github.com/xebialabs-community/xld-lock-plugin/tree/master/src/main/license says community, though there is a badge which says MIT.  Other plug-ins are decorated differently with MIT badges.  Can you clarify?  Thanks

**Comment by jdewinne** [comment]
It should be MIT. (http://xebialabs-community.github.io/)

**Comment by pgroenin** [comment]
Would it be possible to have that actually updated within this repo? As mchip22 stated, the project appears to be set to be MIT licensed, but the actual license file in the repo is still the xebialabs_community.license.

**Comment by pgroenin** [comment]
Thank you so much!
